
services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-videochat}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-videochat}
      POSTGRES_USER: ${POSTGRES_USER:-videochat}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-videochat}", "-U", "${POSTGRES_USER:-videochat}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Use HTTP instead of HTTPS for local development
      SERVER_NAME: ':3000'
      MERCURE_PUBLISHER_JWT_KEY: '${MERCURE_JWT_SECRET:-videochat_mercure_secret_key}'
      MERCURE_SUBSCRIBER_JWT_KEY: '${MERCURE_JWT_SECRET:-videochat_mercure_secret_key}'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins *
        anonymous
    ports:
      - "3000:3000"
    # Comment the following line to enable HTTPS in development mode
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - mercure_data:/data
      - mercure_config:/config
###< symfony/mercure-bundle ###

  php:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - mercure
    environment:
      DATABASE_URL: postgresql://videochat:videochat@database:5432/videochat?serverVersion=16&charset=utf8
      MERCURE_URL: http://mercure:3000/.well-known/mercure
      MERCURE_PUBLIC_URL: http://localhost:3000/.well-known/mercure
      MERCURE_JWT_SECRET: videochat_mercure_secret_key
    volumes:
      - ./:/var/www/videochat:cached

  nginx:
    image: nginx:alpine
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/var/www/videochat/public:ro

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
###< symfony/mercure-bundle ###
