# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    mercure_public_url: '%env(MERCURE_PUBLIC_URL)%'
    # Custom parameters for VideoChat application
    app.signaling_server_url: '%env(default:default_signaling_server_url:SIGNALING_SERVER_URL)%'
    default_signaling_server_url: ~

    # Parametry pro Metered API
    # Defaultní hodnoty pro případ, že proměnné prostředí nejsou nastaveny
    app.metered_api_key: '%env(METERED_API_KEY)%'

    # ExpressTURN server credentials
    app.express_turn.server: '%env(EXPRESS_TURN_SERVER)%'
    app.express_turn.username: '%env(EXPRESS_TURN_USERNAME)%'
    app.express_turn.password: '%env(EXPRESS_TURN_PASSWORD)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Definice TurnCredentialsController s parametry pro Metered API
    App\Controller\TurnCredentialsController:
        arguments:
            $meteredApiKey: '%env(METERED_API_KEY)%'
            $httpClient: '@http_client'
        tags: [ 'controller.service_arguments' ]

    App\Controller\RoomController:
        arguments:
            $signalingServerUrl: '%app.signaling_server_url%'